"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 30000000000

add_newline = true
format = """
$username\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_status\
$git_commit\
$hg_branch\
$pijul_channel\
$fennel\
$guix_shell\
$haxe\
$opa\
$purescript\
$raku\
$rlang\
$red\
$vagrant\
$buf\
$meson\
$spack\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal"""

[directory]
style = 'bold white'

[git_branch]
format = '[$branch(:$remote_branch)]($style) '
style = 'regular gray'

[git_status]
stashed = 's'
conflicted = 'c'
ahead = '↑'
behind = '↓'
diverged = 'd'
untracked = '?'
renamed = '?'
deleted = '-'
up_to_date = '[✓](bold green)'
format = '($all_status$ahead_behind($style) )'

[git_commit]
commit_hash_length = 4
tag_disabled = false
tag_symbol = ''
format= '[$symbol$tag]($style) '
style = 'bold'

[character]
success_symbol = '[>](bold white)'

[package]
disabled = true

[line_break]
disabled = true
